/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp1 {
  MyFlutterApp1._();

  static const _kFontFam = 'MyFlutterApp1';
  static const String? _kFontPkg = null;

  static const IconData threads = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_all = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
