/// Flutter icons MyFlutterApp2
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp2
///      fonts:
///       - asset: fonts/MyFlutterApp2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp2 {
  MyFlutterApp2._();

  static const _kFontFam = 'MyFlutterApp2';
  static const String? _kFontPkg = null;

  static const IconData instagram_reels_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
